export const PHASES = [
  { id: "entry", label: "진입", description: "CLI가 파일을 읽고 VM에 넘긴다." },
  { id: "parse", label: "Parse / AST", description: "Ruff parser가 소스를 AST로 만든다." },
  { id: "collect", label: "심볼 수집", description: "AST를 돌며 DEF/USE 사실과 스코프 트리를 만든다." },
  { id: "resolve", label: "스코프 판정", description: "자식의 free 요구를 부모까지 전파한다." },
  { id: "codegen", label: "코드 생성", description: "AST를 다시 돌며 CFG 명령을 낸다." },
  { id: "bytecode", label: "바이트코드", description: "CFG를 최적화하고 CodeObject로 조립한다." },
  { id: "execute", label: "실행", description: "VM이 CodeObject를 프레임으로 실행한다." },
];

export const SCOPES = [
  {
    name: "top",
    kind: "Module",
    symbols: [
      { name: "rate", scope: "Local", tone: "" },
      { name: "make_counter", scope: "Local", tone: "" },
      { name: "counter", scope: "Local", tone: "" },
      { name: "print", scope: "Unknown", tone: "global" },
    ],
  },
  {
    name: "make_counter",
    kind: "Function",
    symbols: [
      { name: "start", scope: "Local", tone: "" },
      { name: "total", scope: "Cell", tone: "cell" },
      { name: "bump", scope: "Local", tone: "" },
    ],
  },
  {
    name: "bump",
    kind: "Function",
    symbols: [
      { name: "step", scope: "Local", tone: "" },
      { name: "total", scope: "Free", tone: "free" },
      { name: "rate", scope: "GlobalImplicit", tone: "global" },
    ],
  },
];

const sampleStack = ["sample.py"];
const compilerStack = [
  "run_rustpython",
  "VirtualMachine::compile_with_opts",
  "rustpython_compiler::_compile_with_syntax_warning_handler",
];

export const TOUR = [
  {
    id: "sample",
    phase: "entry",
    title: "먼저 하나의 프로그램만 고정한다",
    shortTitle: "추적할 sample.py",
    question: "왜 이 17줄짜리 예제인가?",
    summary:
      "이 예제 하나로 모듈 이름, 함수 로컬, 매개변수, 암시적 전역, nonlocal, Cell, Free를 모두 만든다. 클래스·comprehension·async는 핵심 경로를 흐리므로 이번 실행 슬라이스에서 제외한다.",
    file: "example_projects/compiler-tour/sample.py",
    anchor: "rate = 2",
    endAnchor: "print(counter(3))",
    contextBefore: 0,
    contextAfter: 0,
    stack: sampleStack,
    notes: [
      { match: "rate = 2", text: "모듈에서 rate를 정의한다. 중첩 함수 bump에서는 이 이름이 closure가 아니라 GlobalImplicit가 된다." },
      { match: "def make_counter(start):", text: "함수 정의는 부모 스코프에 make_counter를 바인딩하고, 별도의 Function 심볼 테이블을 만든다." },
      { match: "total = start", text: "total은 make_counter의 로컬이지만 자식 bump가 사용하므로 2차 분석에서 Cell로 승격된다." },
      { match: "nonlocal total", text: "bump의 total은 즉시 Free 후보로 기록되고, 2차 분석에서 실제 바깥 binding이 있는지 검증된다." },
      { match: "total += step * rate", text: "한 줄에서 total은 Load+Store, step은 Local Load, rate는 Global Load가 된다." },
      { match: "print(counter())", text: "컴파일이 끝난 뒤 VM 실행까지 확인할 관찰점이다. 실제 출력은 12, 이어서 18이다." },
    ],
    state: [
      { label: "Mode", value: "Exec" },
      { label: "예상 스코프", value: "Module → make_counter → bump" },
      { label: "핵심 closure", value: "make_counter.total ↔ bump.total" },
      { label: "실행 결과", value: "12\n18" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "top" },
  },
  {
    id: "cli-main",
    phase: "entry",
    title: "바이너리는 Builder를 만들고 run으로 넘긴다",
    shortTitle: "CLI main",
    question: "RustPython 프로세스의 첫 Rust 함수는 무엇을 하는가?",
    summary:
      "main 자체는 8줄뿐이다. 설정 Builder를 만들고, stdlib feature가 있으면 표준 라이브러리를 연결한 뒤 모든 CLI 처리를 rustpython::run에 위임한다.",
    file: "src/main.rs",
    anchor: "pub fn main()",
    endAnchor: "rustpython::run(config)",
    contextBefore: 2,
    contextAfter: 1,
    stack: ["main"],
    notes: [
      { match: "InterpreterBuilder::new", text: "VM을 즉시 실행하지 않고 구성값을 담을 Builder부터 만든다." },
      { match: "config.init_stdlib", text: "stdlib feature가 켜진 빌드에서 native/동결 표준 라이브러리를 등록한다." },
      { match: "rustpython::run(config)", text: "CLI 옵션 해석과 Interpreter 실행의 실제 진입점이다." },
    ],
    state: [
      { label: "입력", value: "argv + process environment" },
      { label: "출력", value: "ExitCode" },
    ],
  },
  {
    id: "runtime-run",
    phase: "entry",
    title: "run이 CLI 모드와 Interpreter를 결합한다",
    shortTitle: "run: 옵션과 VM",
    question: "파일 실행 모드는 언제 결정되는가?",
    summary:
      "parse_opts가 argv를 RunMode로 바꾸고 Builder에 Settings를 넣는다. 그 뒤 Interpreter의 실행 컨텍스트 안에서 run_rustpython을 호출한다. 아직 Python 소스는 파싱하지 않았다.",
    file: "src/lib.rs",
    anchor: "pub fn run(mut builder: InterpreterBuilder)",
    endAnchor: "rustpython_vm::host_env::os::exit_code(exitcode)",
    contextBefore: 1,
    contextAfter: 0,
    stack: ["main", "rustpython::run"],
    notes: [
      { match: "let (settings, run_mode) = match parse_opts()", text: "argv를 Settings와 Command/Module/Script/Repl 중 하나로 정규화한다." },
      { match: "builder = builder.settings(settings)", text: "파싱된 설정을 아직 생성 전인 Interpreter 구성에 합친다." },
      { match: "let interp = builder.interpreter()", text: "여기서 실제 Interpreter/VM 상태가 만들어진다." },
      { match: "run_rustpython(vm, run_mode)", text: "VM 컨텍스트 안으로 RunMode를 이동시켜 파일 실행 경로를 시작한다." },
    ],
    state: [
      { label: "RunMode", value: "Script(sample.py)" },
      { label: "컴파일 상태", value: "아직 시작 전" },
    ],
  },
  {
    id: "route-script",
    phase: "entry",
    title: "Script 분기가 파일 실행기로 라우팅한다",
    shortTitle: "RunMode::Script",
    question: "-c와 파일 실행은 어디에서 갈라지는가?",
    summary:
      "Command는 문자열을 곧바로 vm.run_string에 넘긴다. 현재 예제는 Script이므로 run_file을 거쳐 파일 loader와 __main__ 설정을 적용한다. 컴파일러 관점에서는 둘 다 결국 Mode::Exec로 합류한다.",
    file: "src/lib.rs",
    anchor: "let res = match run_mode",
    endAnchor: "RunMode::Repl => Ok(())",
    contextBefore: 1,
    contextAfter: 1,
    stack: ["main", "rustpython::run", "run_rustpython"],
    notes: [
      { match: "RunMode::Command(command)", text: "-c 소스는 vm.run_string으로 바로 들어간다." },
      { match: "RunMode::Script(script_path)", text: "현재 경로다. sys.path와 loader 설정이 필요한 파일 실행기를 선택한다." },
      { match: "run_file(vm, scope.clone(), &script_path)", text: "파일 읽기와 compile/run의 경계 함수로 이동한다." },
    ],
    state: [
      { label: "선택 분기", value: "RunMode::Script" },
      { label: "공통 종착점", value: "VirtualMachine::compile(..., Mode::Exec)" },
    ],
  },
  {
    id: "read-source",
    phase: "entry",
    title: "파일 bytes를 UTF-8 source로 바꾼다",
    shortTitle: "VM 파일 로더",
    question: "컴파일러가 받는 정확한 입력 타입은 무엇인가?",
    summary:
      "host_env 파일 경로는 bytes를 읽고 NUL을 거부한 뒤 String으로 디코딩한다. 컴파일러에는 &str, Mode::Exec, source path 세 값이 들어간다. 실행은 CodeObject가 돌아온 뒤에만 시작된다.",
    file: "crates/vm/src/vm/python_run.rs",
    anchor: "fn run_simple_file_inner(",
    endAnchor: "self.run_code_obj(code_obj, scope)?;",
    contextBefore: 1,
    contextAfter: 2,
    stack: ["run_rustpython", "run_file", "VirtualMachine::run_simple_file_inner"],
    notes: [
      { match: "match crate::host_env::fs::read(path)", text: "파일 시스템 경계다. 이후 컴파일 파이프라인은 문자열만 다룬다." },
      { match: "let source = String::from_utf8(source_bytes)", text: "source encoding을 String으로 확정한다." },
      { match: ".compile(&source, compiler::Mode::Exec, path)", text: "VM 컴파일 API로 들어간다. 파일 실행은 항상 Exec 모드다." },
      { match: "self.run_code_obj(code_obj, scope)?", text: "컴파일 성공 뒤에만 VM 실행 단계로 넘어간다." },
    ],
    state: [
      { label: "source", value: "&str" },
      { label: "source_path", value: "sample.py" },
      { label: "mode", value: "Mode::Exec" },
    ],
  },
  {
    id: "vm-compile",
    phase: "entry",
    title: "VM이 경고 처리만 감싸고 compiler crate에 위임한다",
    shortTitle: "VM → compiler",
    question: "VM과 독립 컴파일러의 책임 경계는 어디인가?",
    summary:
      "VM은 tokenizer/string 경고를 Python 예외로 승격할 수 있게 handler를 만든다. 실제 parsing과 codegen은 rustpython_compiler에 맡기고, 반환된 compiler-core CodeObject만 VM의 PyCode로 감싼다.",
    file: "crates/vm/src/vm/compile.rs",
    anchor: "pub fn compile_with_opts(",
    endAnchor: "        Ok(code)",
    contextBefore: 1,
    contextAfter: 1,
    stack: ["run_rustpython", "VirtualMachine::compile", "VirtualMachine::compile_with_opts"],
    notes: [
      { match: "emit_tokenizer_syntax_warnings", text: "parser 호출 전, VM warnings 정책에 맞춘 tokenizer 경고를 낸다." },
      { match: "let mut syntax_warning_handler", text: "codegen 도중 발생한 SyntaxWarning을 VM 예외 체계로 돌려보내는 어댑터다." },
      { match: "compiler::compile_with_syntax_warning_handler", text: "여기부터 독립 rustpython-compiler facade의 책임이다." },
      { match: "PyCode::new_ref_from_bytecode", text: "compiler-core CodeObject를 GC가 관리하는 Python code 객체로 변환한다." },
    ],
    state: [
      { label: "VM 책임", value: "warnings + PyCode wrapping" },
      { label: "compiler 책임", value: "parse + symbols + codegen" },
    ],
  },
  {
    id: "compiler-facade",
    phase: "parse",
    title: "facade가 SourceFile을 만든다",
    shortTitle: "compiler::compile",
    question: "왜 raw &str를 바로 Ruff parser에 넣지 않는가?",
    summary:
      "SourceFile은 텍스트와 파일명을 묶어 byte offset을 행·열로 바꾸는 기준이 된다. facade의 public compile은 이 값을 만든 뒤 private _compile로 넘긴다.",
    file: "crates/compiler/src/lib.rs",
    anchor: "pub fn compile(",
    endAnchor: "    _compile(source_file, mode, opts)",
    contextBefore: 1,
    contextAfter: 1,
    stack: [...compilerStack, "rustpython_compiler::compile"],
    notes: [
      { match: "source: &str", text: "VM에서 넘어온 정규화된 Python source다." },
      { match: "let source_file = SourceFileBuilder", text: "오류 위치와 AST range가 공유할 SourceFile을 만든다." },
      { match: "_compile(source_file, mode, opts)", text: "이제 source, mode, options가 하나의 내부 경로로 합류한다." },
    ],
    state: [
      { label: "중심 값", value: "SourceFile" },
      { label: "위치 단위", value: "Ruff TextRange(byte offsets)" },
    ],
  },
  {
    id: "parse-ast",
    phase: "parse",
    title: "Mode를 Ruff mode로 바꾸고 AST를 얻는다",
    shortTitle: "Ruff parse",
    question: "RustPython 자체 parser 코드는 어디까지 읽어야 하는가?",
    summary:
      "현재 parser는 RustPython이 고정한 Ruff fork 외부 의존성이다. 이 투어에서는 mode 매핑, parse 호출, parsed.into_syntax로 AST를 꺼내는 경계까지만 본다. parser 내부는 핵심 2만 줄 범위 밖이다.",
    file: "crates/compiler/src/lib.rs",
    anchor: "fn _compile_with_syntax_warning_handler",
    endAnchor: "    let ast = parsed.into_syntax();",
    contextBefore: 1,
    contextAfter: 3,
    stack: [...compilerStack, "ruff_python_parser::parse"],
    notes: [
      { match: "let parser_mode = match mode", text: "Exec는 Module, Eval은 Expression, Single/BlockExpr도 우선 Module AST로 파싱한다." },
      { match: "let parsed = parser::parse", text: "실제 lex/parse 호출이다. 실패하면 SourceFile을 이용해 CompileError 위치를 만든다." },
      { match: "let ast = parsed.into_syntax()", text: "Parsed 래퍼에서 ruff_python_ast::Mod 소유값을 꺼낸다." },
    ],
    state: [
      { label: "parser mode", value: "ruff::Mode::Module" },
      { label: "AST root", value: "ruff_python_ast::Mod::Module" },
      { label: "parser 구현", value: "RustPython Ruff fork (외부)" },
    ],
  },
  {
    id: "preprocess",
    phase: "parse",
    title: "AST 전처리 뒤 compile mode를 분기한다",
    shortTitle: "compile_top",
    question: "심볼 테이블 전에 AST가 바뀔 수 있는가?",
    summary:
      "future flags를 합치고 finally 경고를 검사한 뒤 preprocess_mod가 최적화 수준과 future annotations에 맞춰 AST를 정리한다. 그 다음 Mod 종류와 Mode에 따라 module/eval/single 경로를 고른다.",
    file: "crates/codegen/src/compile.rs",
    anchor: "pub fn compile_top_with_syntax_warning_handler",
    endAnchor: "    match ast {",
    contextBefore: 0,
    contextAfter: 8,
    stack: [...compilerStack, "compile_top_with_syntax_warning_handler"],
    notes: [
      { match: "checked_future_features", text: "AST 선두의 __future__ import를 먼저 검사해 CodeFlags에 반영한다." },
      { match: "preprocess::preprocess_mod", text: "constant folding과 문장 전처리를 수행한다. 아직 bytecode를 내지는 않는다." },
      { match: "match ast", text: "현재 Mod::Module + Mode::Exec는 compile_program_with_syntax_warning_handler로 간다." },
    ],
    state: [
      { label: "optimize", value: "0" },
      { label: "future_annotations", value: "false" },
      { label: "선택 경로", value: "Module / Exec" },
    ],
  },
  {
    id: "symbols-before-codegen",
    phase: "collect",
    title: "코드 생성 전에 심볼 테이블을 완성한다",
    shortTitle: "2-pass의 바깥 구조",
    question: "왜 AST를 곧바로 bytecode로 바꾸지 않는가?",
    summary:
      "함수 앞부분에서 나중에 나오는 global/nonlocal 선언까지 알아야 첫 이름의 opcode를 정할 수 있다. 그래서 scan_module_symbols가 전체 AST를 먼저 훑고, 완성된 SymbolTable을 Compiler의 두 번째 AST 순회에 넘긴다.",
    file: "crates/codegen/src/compile.rs",
    anchor: "fn compile_program_with_syntax_warning_handler",
    endAnchor: "    Ok(code)",
    contextBefore: 0,
    contextAfter: 1,
    stack: [...compilerStack, "compile_program_with_syntax_warning_handler"],
    notes: [
      { match: "let symbol_table = scan_module_symbols", text: "첫 번째 AST 순회다. raw DEF/USE 수집과 최종 scope 판정을 모두 끝낸다." },
      { match: "let mut compiler = Compiler::new_with_syntax_warning_handler", text: "완성된 심볼 정보가 준비된 뒤에야 codegen 상태를 만든다." },
      { match: "compiler.compile_program(ast, symbol_table)", text: "두 번째 AST 순회다. 이번에는 각 이름에 맞는 opcode와 CFG를 낸다." },
      { match: "let code = compiler.exit_scope", text: "module CFG를 최적화·assemble해 최종 CodeObject로 만든다." },
    ],
    state: [
      { label: "Pass 1", value: "AST → SymbolTable" },
      { label: "Pass 2", value: "AST + SymbolTable → CFG" },
      { label: "마지막", value: "CFG → CodeObject" },
    ],
  },
  {
    id: "symbol-table-shape",
    phase: "collect",
    title: "SymbolTable 하나가 Python block 하나다",
    shortTitle: "SymbolTable 구조",
    question: "심볼 테이블은 평평한 name map인가, 트리인가?",
    summary:
      "각 module/function/class/lambda/comprehension마다 SymbolTable이 하나 생긴다. symbols는 현재 block의 이름만, sub_tables는 AST에서 발견한 순서의 자식 block을 보관한다. 코드 생성기가 같은 순서로 다시 걷기 때문에 이 순서가 중요하다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "pub struct SymbolTable {",
    endAnchor: "    pub sub_tables: Vec<Self>,",
    contextBefore: 3,
    contextAfter: 3,
    stack: [...compilerStack, "SymbolTable"],
    notes: [
      { match: "pub name: String", text: "top, make_counter, bump처럼 block의 표시 이름이다." },
      { match: "pub typ: CompilerScope", text: "Module/Function/Class 등 코드 생성 규칙이 달라지는 block 종류다." },
      { match: "pub symbols: IndexMap<String, Symbol>", text: "현재 block에서 정의되거나 사용된 이름과 그 분석 결과다." },
      { match: "pub sub_tables: Vec<Self>", text: "중첩 block을 AST 방문 순서로 보관한다. 이름 lookup용 map이 아니라 소비 순서가 있는 Vec다." },
    ],
    state: [
      { label: "root", value: "top / Module" },
      { label: "child 0", value: "make_counter / Function" },
      { label: "grandchild", value: "bump / Function" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "top" },
  },
  {
    id: "symbol-vocabulary",
    phase: "collect",
    title: "flags와 최종 scope는 다른 정보다",
    shortTitle: "SymbolScope와 Flags",
    question: "DEF_LOCAL이면 언제나 최종 Local인가?",
    summary:
      "아니다. flags는 1차 방문에서 본 사실이고 scope는 2차 분석의 결론이다. 예를 들어 make_counter.total은 DEF_LOCAL이지만 자식이 요구하므로 Cell이다. bump.total은 DEF_NONLOCAL|DEF_LOCAL|USE이면서 최종 Free다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "pub enum SymbolScope {",
    endAnchor: "pub struct Symbol {",
    contextBefore: 3,
    contextAfter: 7,
    stack: [...compilerStack, "Symbol / SymbolScope / SymbolFlags"],
    notes: [
      { match: "GlobalImplicit", text: "함수 안에서 어떤 enclosing function에도 binding이 없는 이름이다. bump.rate가 여기에 해당한다." },
      { match: "Free", text: "자식 쪽에서 바깥 함수의 cell을 참조한다. bump.total의 최종 scope다." },
      { match: "Cell", text: "정의한 쪽에서 자식에게 closure storage를 제공한다. make_counter.total의 최종 scope다." },
      { match: "const DEF_NONLOCAL", text: "nonlocal 문장을 보았다는 raw 사실이다. binding 유효성은 2차 pass가 검사한다." },
      { match: "pub scope: SymbolScope", text: "최종 opcode 선택에 직접 쓰이는 별도 필드다." },
      { match: "pub flags: SymbolFlags", text: "AST에서 관찰한 정의/사용 사실을 잃지 않고 별도로 보관한다." },
    ],
    state: [
      { label: "total@outer", value: "flags=DEF_LOCAL, scope=Cell" },
      { label: "total@bump", value: "flags=DEF_NONLOCAL|DEF_LOCAL|USE, scope=Free" },
      { label: "rate@bump", value: "flags=USE, scope=GlobalImplicit" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "bump" },
  },
  {
    id: "scan-program",
    phase: "collect",
    title: "scan_program이 Builder의 생명주기를 닫는다",
    shortTitle: "수집 pass 진입",
    question: "심볼 테이블 public API는 어떤 세 호출로 이루어지는가?",
    summary:
      "Builder 생성, module body 순회, finish 세 단계뿐이다. 옵션은 top-level await, future annotations, compiler recursion limit을 Builder 상태에 옮긴다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "pub fn scan_program_with_options(",
    endAnchor: "        builder.finish()",
    contextBefore: 1,
    contextAfter: 1,
    stack: [...compilerStack, "SymbolTable::scan_program_with_options"],
    notes: [
      { match: "let mut builder = SymbolTableBuilder::new", text: "빈 builder가 아니라 생성 시점에 이미 top Module scope가 들어간 builder다." },
      { match: "builder.scan_statements", text: "1차 AST walk: 이름의 사용 사실과 중첩 block 구조를 수집한다." },
      { match: "builder.finish()", text: "stack을 닫고 2차 scope 분석까지 실행한 최종 SymbolTable을 반환한다." },
    ],
    state: [
      { label: "입력", value: "&ast::ModModule" },
      { label: "출력", value: "Result<SymbolTable>" },
    ],
  },
  {
    id: "builder-scope-stack",
    phase: "collect",
    title: "Builder는 현재 block을 명시적 stack으로 관리한다",
    shortTitle: "enter_scope",
    question: "중첩 def를 만났을 때 현재 심볼 map은 어떻게 바뀌는가?",
    summary:
      "새 SymbolTable을 tables에 push하면 tables.last()가 새 현재 scope가 된다. 부모가 함수 계열이면 is_nested가 전파되고, varnames는 별도 stack에 보존된다. leave_scope는 이 테이블을 pop해 부모 sub_tables에 붙인다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "fn enter_scope(&mut self, name: &str, typ: CompilerScope",
    endAnchor: ".push(core::mem::take(&mut self.current_varnames));",
    contextBefore: 1,
    contextAfter: 1,
    stack: [...compilerStack, "SymbolTableBuilder::enter_scope"],
    notes: [
      { match: "let parent = self.tables.last()", text: "push 전의 last가 lexical parent다." },
      { match: "let is_nested", text: "부모가 이미 nested이거나 function-like면 새 block도 nested다." },
      { match: "let mut table = SymbolTable::new", text: "이름·종류·행·nested 상태를 가진 빈 현재 block을 만든다." },
      { match: "self.tables.push(table)", text: "이 줄 이후 register_name은 새 block의 symbols를 수정한다." },
      { match: "self.varnames_stack", text: "부모의 parameter 순서를 보관하고 자식용 빈 목록을 시작한다." },
    ],
    state: [
      { label: "rate", value: "tables=[top]" },
      { label: "make_counter body", value: "tables=[top, make_counter]" },
      { label: "bump body", value: "tables=[top, make_counter, bump]" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "make_counter" },
  },
  {
    id: "scan-function-def",
    phase: "collect",
    title: "FunctionDef는 부모와 자식을 모두 건드린다",
    shortTitle: "FunctionDef 방문",
    question: "def make_counter를 방문하는 정확한 순서는 무엇인가?",
    summary:
      "함수 이름·default·decorator는 부모 scope에서 처리한다. 그 뒤 함수 scope를 열고 parameter와 body를 수집해 자식 테이블로 닫는다. default가 함수 로컬을 볼 수 없는 이유가 이 순서에 드러난다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "Stmt::FunctionDef(StmtFunctionDef {",
    endAnchor: "                    self.scan_statements(body)?;",
    contextBefore: 1,
    contextAfter: 5,
    stack: [...compilerStack, "SymbolTableBuilder::scan_statement(FunctionDef)"],
    notes: [
      { match: "self.register_name(name.as_str(), SymbolUsage::Assigned", text: "make_counter 또는 bump 이름을 현재 부모 block의 DEF_LOCAL로 기록한다." },
      { match: "self.scan_parameter_defaults(parameters)", text: "bump(step=1)의 1은 make_counter scope에서 먼저 평가된다." },
      { match: "self.enter_scope_with_parameters", text: "새 Function table을 push하고 start/step 같은 parameter를 등록한다." },
      { match: "self.scan_statements(body)", text: "현재 tables.last()가 함수 table인 상태로 body 전체를 순회한다." },
      { match: "self.leave_scope()", text: "완성한 함수 table을 부모 sub_tables에 AST 순서대로 붙인다." },
    ],
    state: [
      { label: "부모에 기록", value: "function name + defaults + decorators" },
      { label: "자식에 기록", value: "parameters + body names" },
    ],
  },
  {
    id: "scan-name",
    phase: "collect",
    title: "Name node의 context를 SymbolUsage로 바꾼다",
    shortTitle: "Name 방문",
    question: "total += ... 같은 이름은 어떻게 DEF와 USE를 모두 얻는가?",
    summary:
      "AST가 제공한 load/store 문맥을 Used/Assigned/Iter로 매핑한다. AugAssign visitor가 target을 load와 store 양쪽으로 방문하므로 total에 USE와 DEF_LOCAL이 함께 쌓인다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "Expr::Name(ExprName { id, range, .. })",
    endAnchor: "self.register_name(\"__class__\", SymbolUsage::Used, *range)?;",
    contextBefore: 1,
    contextAfter: 3,
    stack: [...compilerStack, "SymbolTableBuilder::scan_expression(Name)"],
    notes: [
      { match: "self.check_name(id, context", text: "__debug__ 할당/삭제처럼 context만으로 알 수 있는 문법 오류를 먼저 막는다." },
      { match: "ExpressionContext::Load", text: "값을 읽는 Name은 SymbolUsage::Used로 변환된다." },
      { match: "ExpressionContext::Store", text: "binding을 만드는 Name은 SymbolUsage::Assigned로 변환된다." },
      { match: "id == \"super\"", text: "함수에서 super를 읽으면 암시적 __class__ 사용도 기록하는 특수 규칙이다." },
    ],
    state: [
      { label: "step", value: "Load → USE" },
      { label: "rate", value: "Load → USE" },
      { label: "total +=", value: "Load + Store → USE|DEF_LOCAL" },
    ],
  },
  {
    id: "register-flags",
    phase: "collect",
    title: "register_name은 아직 대부분 scope를 결정하지 않는다",
    shortTitle: "raw facts 기록",
    question: "첫 pass가 확정하는 것과 미루는 것은 무엇인가?",
    summary:
      "Assigned/Used/Parameter는 flags만 더한다. Global과 Nonlocal처럼 선언 자체가 의미를 확정하는 경우만 scope를 즉시 기록한다. Local/Cell/GlobalImplicit 구분은 자식과 부모를 봐야 하므로 finish까지 미룬다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "// Set proper scope and flags on symbol:",
    endAnchor: "            SymbolUsage::TypeParam => {",
    contextBefore: 2,
    contextAfter: 4,
    stack: [...compilerStack, "SymbolTableBuilder::register_name"],
    notes: [
      { match: "SymbolUsage::Nonlocal", text: "nonlocal은 Free 후보와 DEF_NONLOCAL을 즉시 기록하지만, binding 존재 검증은 2차 pass다." },
      { match: "SymbolUsage::Parameter", text: "DEF_PARAM을 기록하고 varnames 순서를 보존한다." },
      { match: "SymbolUsage::Assigned", text: "DEF_LOCAL 사실만 기록한다. 최종 Cell일 수도 있다." },
      { match: "SymbolUsage::Global", text: "명시적 global은 GlobalExplicit와 DEF_GLOBAL을 즉시 확정한다." },
      { match: "SymbolUsage::Used", text: "USE만으로는 Local/Free/Global 중 무엇인지 아직 알 수 없다." },
    ],
    state: [
      { label: "Pass 1 산출", value: "flags + scope tree" },
      { label: "대부분의 scope", value: "Unknown" },
    ],
  },
  {
    id: "finish-first-pass",
    phase: "resolve",
    title: "finish가 수집 결과를 분석 결과로 바꾼다",
    shortTitle: "pass 경계",
    question: "디버거로 raw flags와 최종 scope를 나란히 보려면 어디에 멈추는가?",
    summary:
      "루트 table을 pop한 직후가 raw 수집 결과다. analyze_symbol_table 호출 뒤 반환 직전이 최종 결과다. 이 함수가 두 pass 사이의 가장 명확한 breakpoint다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "fn finish(mut self)",
    endAnchor: "        Ok(symbol_table)",
    contextBefore: 1,
    contextAfter: 1,
    stack: [...compilerStack, "SymbolTableBuilder::finish"],
    notes: [
      { match: "assert_eq!(self.tables.len(), 1)", text: "모든 중첩 scope가 닫혀 루트 top만 남았는지 확인한다." },
      { match: "let mut symbol_table = self.tables.pop", text: "이 순간의 symbols는 raw flags 중심이며 많은 scope가 Unknown이다." },
      { match: "analyze_symbol_table(&mut symbol_table)", text: "자식부터 재귀 분석해 Free를 전파하고 부모 Local을 Cell로 승격한다." },
      { match: "Ok(symbol_table)", text: "코드 생성기가 소비할 최종 scope까지 채워진 트리다." },
    ],
    state: [
      { label: "권장 BP", value: "symboltable.rs / finish" },
      { label: "before", value: "DEF/USE facts" },
      { label: "after", value: "Local/Cell/Free/Global" },
    ],
  },
  {
    id: "analyze-children",
    phase: "resolve",
    title: "2차 분석은 자식부터 올라온다",
    shortTitle: "재귀 free 전파",
    question: "부모가 Cell인지 자식을 보기 전에 알 수 있는가?",
    summary:
      "알 수 없다. 현재 symbols를 잠시 ancestor stack에 넣고 모든 child table을 먼저 분석한다. child가 반환한 free 이름 집합을 모은 다음에야 현재 block의 symbol을 Cell 또는 Local로 판정한다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "    fn analyze_symbol_table(",
    endAnchor: "        symbol_table.symbols = info.0;",
    contextBefore: 2,
    contextAfter: 6,
    stack: [...compilerStack, "SymbolTableAnalyzer::analyze_symbol_table"],
    notes: [
      { match: "let symbols = core::mem::take", text: "현재 map을 table에서 꺼내 ancestor 분석 stack에 넣을 준비를 한다." },
      { match: "for sub_table in sub_tables.iter_mut()", text: "bump를 make_counter보다 먼저 최종 분류한다." },
      { match: "let child_free = inner_scope.analyze_symbol_table", text: "각 자식이 해결하지 못하고 바깥에 요구하는 free set을 반환한다." },
      { match: "child_frees.push", text: "부모는 자식별 free 집합을 모아 Cell 승격과 PEP 709 처리를 준비한다." },
      { match: "symbol_table.symbols = info.0", text: "자식 분석 중 추가된 synthetic Free 이름까지 포함한 현재 map을 복원한다." },
    ],
    state: [
      { label: "분석 순서", value: "bump → make_counter → top" },
      { label: "bump가 반환", value: "{ total }" },
      { label: "rate", value: "module은 closure parent가 아니므로 미반환" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "bump" },
  },
  {
    id: "analyze-symbol",
    phase: "resolve",
    title: "이름 하나를 최종 scope로 분류한다",
    shortTitle: "analyze_symbol",
    question: "Unknown 이름이 Local, Cell, Free, GlobalImplicit 중 하나가 되는 규칙은?",
    summary:
      "현재 block에서 bound면 자식이 Free로 요구하는지 보고 Local/Cell을 고른다. bound가 아니면 enclosing function에서 찾으면 Free, 못 찾고 ancestor가 있으면 GlobalImplicit다. 루트의 미정의 이름은 이 구현에서 Unknown으로 남는다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "    fn analyze_symbol(",
    endAnchor: "                symbol.scope = scope;",
    contextBefore: 1,
    contextAfter: 3,
    stack: [...compilerStack, "SymbolTableAnalyzer::analyze_symbol"],
    notes: [
      { match: "SymbolScope::Free =>", text: "nonlocal처럼 이미 Free인 이름은 실제 바깥 binding이 있는지 검증한다." },
      { match: "if symbol.is_bound()", text: "DEF_LOCAL/DEF_PARAM/DEF_IMPORT가 있으면 현재 block이 이 binding의 소유자다." },
      { match: "self.found_in_inner_scope", text: "자식이 동일 이름을 Free로 요구하면 Local 대신 Cell을 반환한다." },
      { match: "self.found_in_outer_scope", text: "현재 binding이 없을 때 enclosing function의 binding을 찾으면 Free다." },
      { match: "SymbolScope::GlobalImplicit", text: "함수 ancestor가 있지만 어느 enclosing function에도 binding이 없으면 전역 lookup이다." },
      { match: "symbol.scope = scope", text: "최종 결론을 flags와 별개인 scope 필드에 쓴다." },
    ],
    state: [
      { label: "make_counter.total", value: "bound + child Free → Cell" },
      { label: "bump.total", value: "nonlocal + outer binding → Free" },
      { label: "bump.rate", value: "no outer function binding → GlobalImplicit" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "make_counter" },
  },
  {
    id: "find-outer",
    phase: "resolve",
    title: "Free는 module이 아니라 enclosing function에서 찾는다",
    shortTitle: "outer binding 검색",
    question: "왜 bump.rate는 Free가 아닌 GlobalImplicit인가?",
    summary:
      "found_in_outer_scope는 일반 이름에 대해 Module과 Class를 closure binding 후보에서 건너뛴다. 따라서 module의 rate는 lexical cell이 되지 않는다. 반대로 make_counter의 total은 function binding이므로 bump에서 Free가 된다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "fn found_in_outer_scope(",
    endAnchor: "        decl_depth.map(|_| SymbolScope::Free)",
    contextBefore: 1,
    contextAfter: 1,
    stack: [...compilerStack, "SymbolTableAnalyzer::found_in_outer_scope"],
    notes: [
      { match: "matches!(typ, CompilerScope::Module)", text: "module binding은 closure capture 후보가 아니다. 런타임 globals dict에서 찾는다." },
      { match: "if let Some(sym) = symbols.get(name)", text: "enclosing function map에서 같은 이름을 찾는다." },
      { match: "if sym.is_bound()", text: "parameter/local/import처럼 binding을 소유한 이름이면 탐색을 멈춘다." },
      { match: "decl_depth = Some(i)", text: "binding과 현재 block 사이의 깊이를 기억한다." },
      { match: "decl_depth.map(|_| SymbolScope::Free)", text: "function binding을 찾은 경우 현재 이름의 결론은 Free다." },
    ],
    state: [
      { label: "total 검색", value: "make_counter에서 발견 → Free" },
      { label: "rate 검색", value: "Module은 skip → GlobalImplicit" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "bump" },
  },
  {
    id: "promote-cell",
    phase: "resolve",
    title: "자식의 Free가 부모의 Cell을 만든다",
    shortTitle: "Cell 승격",
    question: "Cell은 어느 방향의 정보인가?",
    summary:
      "자식 bump에서 total이 Free라는 사실을 먼저 만든다. 부모 make_counter에서 같은 이름이 bound인 상태로 자식 Free를 발견하면 Cell을 반환한다. 즉 Free는 참조하는 쪽, Cell은 저장 공간을 제공하는 쪽이다.",
    file: "crates/codegen/src/symboltable.rs",
    anchor: "fn found_in_inner_scope(",
    endAnchor: "        })",
    contextBefore: 1,
    contextAfter: 1,
    stack: [...compilerStack, "SymbolTableAnalyzer::found_in_inner_scope"],
    notes: [
      { match: "sub_tables.iter().find_map", text: "현재 block의 직접 자식들을 살펴본다." },
      { match: "let sym = st.symbols.get(name)?", text: "자식 안에 동일한 이름이 실제로 있는지 확인한다." },
      { match: "sym.scope == SymbolScope::Free", text: "자식이 바깥 저장 공간을 요구하는 이름인지 확인한다." },
      { match: "Some(SymbolScope::Cell)", text: "현재 block의 bound 이름을 Cell로 승격시킨다." },
    ],
    state: [
      { label: "bump.total", value: "Free" },
      { label: "make_counter.total", value: "Cell" },
      { label: "런타임 연결", value: "같은 PyCell storage" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "make_counter" },
  },
  {
    id: "trace-symbols",
    phase: "resolve",
    title: "작은 Rust 도구로 최종 트리를 그대로 출력한다",
    shortTitle: "실제 관찰 도구",
    question: "Python symtable 모듈 대신 왜 Rust API를 직접 쓰는가?",
    summary:
      "현재 Python _symtable 어댑터는 Symbol.scope를 flags 상위 비트에 합치지 않아 공개 symtable이 Free/Cell을 잃는다. 이 프로젝트는 compile_symtable 반환값의 public fields를 재귀 출력해 내부 실제 결과를 보존한다.",
    file: "example_projects/compiler-tour/src/main.rs",
    anchor: "fn print_symbol_table(",
    endAnchor: "        print_symbol_table(child, depth + 1);",
    contextBefore: 1,
    contextAfter: 2,
    stack: ["compiler-tour::run", "compile_symtable", "print_symbol_table"],
    notes: [
      { match: "table.name, table.typ", text: "각 block의 이름과 CompilerScope를 그대로 출력한다." },
      { match: "for symbol in table.symbols.values()", text: "가공된 integer가 아니라 내부 Symbol을 직접 순회한다." },
      { match: "symbol.scope", text: "2차 분석의 최종 Local/Cell/Free/Global 결론이다." },
      { match: "format_flags(symbol.flags)", text: "최종 scope와 raw DEF/USE facts를 나란히 보여준다." },
      { match: "for child in &table.sub_tables", text: "AST 순서의 scope tree를 재귀 출력한다." },
    ],
    state: [
      { label: "명령", value: "cargo run --manifest-path example_projects/compiler-tour/Cargo.toml" },
      { label: "데이터 원본", value: "rustpython_compiler::compile_symtable" },
      { label: "공개 symtable", value: "현재 scope-bit 누락 — 사용 안 함" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "bump" },
  },
  {
    id: "compiler-state",
    phase: "codegen",
    title: "Compiler는 code stack과 symbol stack을 함께 움직인다",
    shortTitle: "Compiler 상태",
    question: "두 번째 AST walk에서 현재 scope를 어떻게 기억하는가?",
    summary:
      "code_stack은 module과 중첩 함수의 CFG/metadata를, symbol_table_stack은 같은 lexical 위치의 분석 결과를 보관한다. FunctionDef에 진입할 때 두 stack을 함께 push하고 함수 CodeObject를 만들 때 함께 pop한다.",
    file: "crates/codegen/src/compile.rs",
    anchor: "struct Compiler<'a> {",
    endAnchor: "syntax_warning_handler: Option<&'a mut SyntaxWarningHandler<'a>>",
    contextBefore: 3,
    contextAfter: 1,
    stack: [...compilerStack, "Compiler"],
    notes: [
      { match: "code_stack: Vec<ir::CodeInfo>", text: "각 활성 code scope의 CFG와 names/consts/varnames metadata를 쌓는다." },
      { match: "symbol_table_stack: Vec<SymbolTable>", text: "동일한 활성 scope의 최종 name resolution을 쌓는다." },
      { match: "current_source_range", text: "emit되는 명령에 원본 source 위치를 붙이는 현재 AST 범위다." },
      { match: "ctx: CompileContext", text: "현재가 함수/클래스/async 안인지에 따라 name과 문장 코드를 바꾼다." },
      { match: "opts: CompileOpts", text: "최적화, debug ranges, recursion limit 같은 컴파일 옵션이다." },
    ],
    state: [
      { label: "module", value: "code_stack=1, symbol_stack=1" },
      { label: "inside make_counter", value: "2 / 2" },
      { label: "inside bump", value: "3 / 3" },
    ],
  },
  {
    id: "compile-module",
    phase: "codegen",
    title: "완성된 root table을 push하고 AST를 다시 걷는다",
    shortTitle: "module codegen",
    question: "두 번째 pass가 시작될 때 무엇이 이미 확정되어 있는가?",
    summary:
      "모든 Symbol.scope가 확정된 root table을 stack에 push하고 module Resume/pseudo prefix를 낸다. 이후 compile_statements가 같은 AST body를 다시 방문하지만 이번에는 이름을 등록하지 않고 명령을 emit한다.",
    file: "crates/codegen/src/compile.rs",
    anchor: "fn compile_program(",
    endAnchor: "        self.compile_statements(statements)?;",
    contextBefore: 1,
    contextAfter: 5,
    stack: [...compilerStack, "Compiler::compile_program"],
    notes: [
      { match: "self.symbol_table_stack.push(symbol_table)", text: "분석이 끝난 top table을 현재 codegen scope로 설치한다." },
      { match: "self.emit_resume_for_scope", text: "module CodeObject의 첫 실행 prefix를 CFG에 추가한다." },
      { match: "let (doc, statements) = split_doc_with_range", text: "docstring을 별도 constant/metadata로 처리하고 실제 문장 slice를 얻는다." },
      { match: "self.compile_statements(statements)", text: "sample.py의 Assign, FunctionDef, Call을 순서대로 두 번째 방문한다." },
    ],
    state: [
      { label: "현재 table", value: "top / Module" },
      { label: "첫 명령", value: "RESUME" },
      { label: "다음", value: "compile_statement × module.body" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "top" },
  },
  {
    id: "compile-function",
    phase: "codegen",
    title: "중첩 함수는 별도 code scope로 컴파일한 뒤 closure로 감싼다",
    shortTitle: "function + closure",
    question: "bump의 CodeObject는 언제 부모 constant가 되는가?",
    summary:
      "enter_function이 child symbol table과 새 CodeInfo를 push한다. body를 컴파일하고 exit_scope로 child CodeObject를 완성한 뒤, make_closure가 freevars에 맞는 부모 cell을 로드해 함수 객체 생성 명령을 낸다.",
    file: "crates/codegen/src/compile.rs",
    anchor: "fn compile_function_body(",
    endAnchor: "        self.make_closure(code, funcflags)?;",
    contextBefore: 2,
    contextAfter: 4,
    stack: [...compilerStack, "Compiler::compile_function_body"],
    notes: [
      { match: "self.enter_function(name, parameters)", text: "다음 child SymbolTable을 소비하고 함수용 CodeInfo를 code_stack에 push한다." },
      { match: "self.compile_statements(body)", text: "함수 body AST를 현재 함수의 분석 결과로 컴파일한다." },
      { match: "let code = self.exit_scope()", text: "함수 CFG를 finalize해 독립 CodeObject로 만들고 두 stack을 pop한다." },
      { match: "self.make_closure(code, funcflags)", text: "child freevars를 부모 cell/free 슬롯과 연결한 뒤 MakeFunction 계열 명령을 낸다." },
    ],
    state: [
      { label: "make_counter cellvars", value: "[total]" },
      { label: "bump freevars", value: "[total]" },
      { label: "bump globals", value: "rate" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "bump" },
  },
  {
    id: "compile-name",
    phase: "codegen",
    title: "compile_name이 scope를 opcode family로 바꾼다",
    shortTitle: "scope → opcode",
    question: "Local, Cell, Free, Global이 실제로 어디서 LOAD_*가 되는가?",
    summary:
      "현재 SymbolTable에서 이름을 찾아 actual_scope를 얻고 실행 context와 결합해 Fast/Deref/Global/Name을 고른다. 마지막 match가 Load/Store/Delete에 맞는 구체 instruction을 emit한다.",
    file: "crates/codegen/src/compile.rs",
    anchor: "fn compile_name(&mut self, name: &str, usage: NameUsage)",
    endAnchor: "            NameOp::Name => {",
    contextBefore: 2,
    contextAfter: 18,
    stack: [...compilerStack, "Compiler::compile_name"],
    notes: [
      { match: "let (symbol_scope, can_see_class_scope", text: "현재 table에서 분석된 Symbol.scope를 읽는다." },
      { match: "let op_type = match actual_scope", text: "Free/Cell→Deref, 함수 Local→Fast, 함수 Global→Global, module Local→Name으로 줄인다." },
      { match: "SymbolScope::Free => NameOp::Deref", text: "bump.total은 Deref family다." },
      { match: "NameOp::Fast =>", text: "bump.step과 make_counter.start는 Fast local slot을 쓴다." },
      { match: "emit!(self, Instruction::LoadDeref { i });", text: "Free/Cell 값을 closure slot에서 읽는 일반 함수 경로의 실제 instruction이다." },
      { match: "Instruction::LoadFast", text: "함수 로컬 값을 localsplus slot에서 읽는 실제 instruction이다." },
      { match: "NameOp::Global =>", text: "bump.rate는 names/global dict lookup 명령으로 간다." },
    ],
    state: [
      { label: "total@bump", value: "Free → Load/StoreDeref" },
      { label: "step@bump", value: "Local → LoadFast" },
      { label: "rate@bump", value: "GlobalImplicit → LoadGlobal" },
      { label: "rate@module", value: "Local → StoreName" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "bump" },
  },
  {
    id: "emit-cfg",
    phase: "codegen",
    title: "emit은 아직 byte 배열을 쓰지 않는다",
    shortTitle: "Instruction → CFG",
    question: "emit!(LoadDeref)는 곧바로 2-byte CodeUnit인가?",
    summary:
      "아니다. _emit은 opcode·arg·target·source range를 InstructionInfo로 만들어 현재 CFG block에 추가한다. jump target과 pseudo instruction, stack depth를 다듬기 전의 고수준 중간 표현이다.",
    file: "crates/codegen/src/compile.rs",
    anchor: "fn _emit<I: Into<AnyInstruction>>",
    endAnchor: "        self.cpython_cfg_builder_addop(ir::InstructionInfo {",
    contextBefore: 2,
    contextAfter: 10,
    stack: [...compilerStack, "Compiler::_emit"],
    notes: [
      { match: "let instr = instr.into()", text: "typed Instruction/PseudoInstruction을 공통 AnyInstruction으로 바꾼다." },
      { match: "let opcode = AnyOpcode::from(instr)", text: "argument/target 규칙을 검증할 opcode view를 만든다." },
      { match: "let range = self.current_source_range", text: "현재 AST node의 byte range를 명령 위치에 연결한다." },
      { match: "source.source_location", text: "byte offset을 사람이 보는 line/column으로 변환한다." },
      { match: "ir::InstructionInfo", text: "opcode, full OpArg, CFG target, source locations를 가진 IR 레코드다." },
    ],
    state: [
      { label: "아직 남은 것", value: "CFG optimize + jump resolve + assemble" },
      { label: "현재 arg", value: "u32 OpArg" },
      { label: "최종 CodeUnit", value: "opcode byte + arg byte" },
    ],
  },
  {
    id: "finalize-code",
    phase: "bytecode",
    title: "finalize_code가 CFG를 선형 bytecode로 조립한다",
    shortTitle: "CFG → CodeObject",
    question: "control-flow graph는 어떤 순서로 최종 형태가 되는가?",
    summary:
      "codegen CFG를 준비하고 optimization을 적용한 뒤 stack depth와 localsplus를 계산한다. jump label을 offset으로 바꾸고 assemble_emit이 instruction bytes, line table, exception table을 만든다.",
    file: "crates/codegen/src/ir.rs",
    anchor: "pub fn finalize_code(",
    endAnchor: "        Ok(CodeObject {",
    contextBefore: 1,
    contextAfter: 24,
    stack: [...compilerStack, "CodeInfo::finalize_code"],
    notes: [
      { match: "let instr_sequence = self.prepare_cfg_from_codegen", text: "codegen이 만든 blocks를 optimizer가 소비할 instruction sequence와 정합시킨다." },
      { match: "optimize_code_unit", text: "dead blocks, redundant operations 등 CFG 최적화 pipeline을 적용한다." },
      { match: "optimized_cfg_to_instruction_sequence", text: "pseudo op lowering, stack depth, localsplus, jump normalization을 수행한다." },
      { match: "resolve_jump_offsets", text: "CFG target을 선형 instruction offset으로 확정한다." },
      { match: "let assembled = assemble_emit", text: "EXTENDED_ARG를 포함한 실제 CodeUnit 배열과 위치/예외 테이블을 인코딩한다." },
      { match: "Ok(CodeObject", text: "bytecode와 모든 metadata를 하나의 compiler-core 값으로 묶는다." },
    ],
    state: [
      { label: "입력", value: "ir::CodeInfo + CFG Blocks" },
      { label: "중간", value: "InstructionSequence" },
      { label: "출력", value: "compiler_core::CodeObject" },
    ],
  },
  {
    id: "code-object",
    phase: "bytecode",
    title: "CodeObject는 실행 코드와 name-resolution 결과를 함께 담는다",
    shortTitle: "최종 산출물",
    question: "심볼 테이블의 흔적은 최종 객체 어디에 남는가?",
    summary:
      "SymbolTable 자체는 런타임에 들고 가지 않는다. 그 결론은 선택된 instructions와 varnames/cellvars/freevars 배열로 압축된다. nested 함수 CodeObject는 부모 constants 안에 들어간다.",
    file: "crates/compiler-core/src/bytecode.rs",
    anchor: "pub struct CodeObject<C: Constant = ConstantData> {",
    endAnchor: "    pub exceptiontable: Box<[u8]>,",
    contextBefore: 5,
    contextAfter: 1,
    stack: [...compilerStack, "CodeObject"],
    notes: [
      { match: "pub instructions: CodeUnits", text: "VM dispatch가 읽을 2-byte code units다." },
      { match: "pub constants: Constants", text: "정수/문자열뿐 아니라 make_counter와 bump의 nested CodeObject도 들어간다." },
      { match: "pub names: Box", text: "LoadGlobal/LoadName 등이 index로 참조하는 이름 table이다." },
      { match: "pub varnames: Box", text: "Fast local slot 이름 배열이다." },
      { match: "pub cellvars: Box", text: "현재 code가 소유하고 자식에게 제공하는 closure slot이다." },
      { match: "pub freevars: Box", text: "부모 closure에서 공급받는 slot 이름이다." },
      { match: "pub linetable", text: "instruction offset을 source 위치에 다시 연결한다." },
    ],
    state: [
      { label: "make_counter.cellvars", value: "[total]" },
      { label: "bump.freevars", value: "[total]" },
      { label: "bump.varnames", value: "[step]" },
      { label: "bump.names", value: "[rate]" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "bump" },
  },
  {
    id: "vm-execute",
    phase: "execute",
    title: "VM은 module CodeObject도 함수처럼 호출한다",
    shortTitle: "CodeObject 실행",
    question: "컴파일과 실행이 맞닿는 마지막 함수는 무엇인가?",
    summary:
      "run_code_obj_with_closure가 module code를 PyFunction으로 감싸고 globals/locals scope와 함께 호출한다. 이후 frame dispatch loop가 LoadFast/LoadDeref/LoadGlobal 같은 앞 단계의 결정을 실행한다. VM 내부는 이번 투어의 비핵심이므로 이 경계에서 멈춘다.",
    file: "crates/vm/src/vm/mod.rs",
    anchor: "pub fn run_code_obj(&self, code: PyRef<PyCode>",
    endAnchor: "        func.invoke_with_locals(FuncArgs::default(), scope.locals, self)",
    contextBefore: 1,
    contextAfter: 1,
    stack: ["VirtualMachine::run_code_obj", "run_code_obj_with_closure", "PyFunction::invoke_with_locals", "frame dispatch loop"],
    notes: [
      { match: "self.run_code_obj_with_closure(code, scope, None)", text: "module에는 외부 closure가 없으므로 None으로 공통 실행 경로를 탄다." },
      { match: "let mut func = PyFunction::new", text: "module CodeObject도 globals를 가진 호출 가능한 PyFunction으로 감싼다." },
      { match: "func.closure = closure", text: "nested 함수라면 앞서 만든 cell tuple이 여기에 연결된다." },
      { match: "func.invoke_with_locals", text: "frame을 만들고 bytecode dispatch를 시작하는 다음 경계다." },
    ],
    state: [
      { label: "실행 출력", value: "12\n18" },
      { label: "total storage", value: "PyCell: 10 → 12 → 18" },
      { label: "rate lookup", value: "module globals: 2" },
      { label: "투어 경계", value: "frame dispatch는 가볍게만 확인" },
    ],
    visual: { scopes: ["top", "make_counter", "bump"], active: "top" },
  },
];
